// Property data — edit values here OR via Tweaks panel
window.WEEKLY_DATA = /*EDITMODE-BEGIN*/{
  "weekLabel": "WEEK OF APR 22, 2026",
  "headline": "This Week's NoCo Investment Picks",
  "subhead": "Three Northern Colorado picks pulled from Laura's weekly investor shortlist \u2014 cash-flow, returns, and diversification.",
  "p1_pick": "PICK 01",
  "p1_angle": "THE CASH-FLOW STORY",
  "p1_address": "1117 16th St",
  "p1_city": "Greeley, CO",
  "p1_type": "Duplex \u00b7 STR/MTR-operating",
  "p1_metric_value": "$5K\u2013$7K",
  "p1_metric_label": "Monthly gross (listed)",
  "p1_chip1": "Turnkey",
  "p1_chip2": "Walk to UNC",
  "p1_chip3": "1914 Craftsman",
  "p2_pick": "PICK 02",
  "p2_angle": "THE RETURNS STORY",
  "p2_address": "1940 29th Ave",
  "p2_city": "Greeley, CO",
  "p2_type": "Ranch condo \u00b7 Standalone",
  "p2_metric_value": "Under $90K",
  "p2_metric_label": "Entry point",
  "p2_chip1": "Best cap rate",
  "p2_chip2": "$545/mo HOA",
  "p2_chip3": "2-car garage",
  "p3_pick": "PICK 03",
  "p3_angle": "THE DIVERSIFICATION STORY",
  "p3_address": "1016 Deborah Dr",
  "p3_city": "Loveland, CO",
  "p3_type": "Single-level ranch \u00b7 Move-in ready",
  "p3_metric_value": "0.22 AC",
  "p3_metric_label": "Cul-de-sac lot",
  "p3_chip1": "6 days on market",
  "p3_chip2": "Move-in ready",
  "p3_chip3": "Diversify",
  "agentName": "Laura MacDonald",
  "agentHandle": "@LauraMacRealtor",
  "agentPhone": "970.966.3207",
  "agentEmail": "Lauramacrealtor@gmail.com",
  "cta": "Comment INVEST below for the full breakdown"
}/*EDITMODE-END*/;
